#!/bin/bash
spgw_iface_name=`ip addr | awk -v FS=": " '/BROADCAST/{print $2}'`
if [ $# -lt 1 ]; then
  echo "Errors... Need agrs"
  echo "Usage: ./spgw-set-addr -i spgw-ip"
  echo "Examples: ./mme-set-addr -i 192.168.12.12/24"
  exit 1
fi
case "$1" in
  -i)
  spgw_addr=$2
  ;;
  *)
  echo "Usage: ./spgw_set-addr -ispgw-ip"
  echo "Examples: ./mme-set-addr -i 192.168.12.12/24"
  exit 1
  ;;
esac
spgw_conf=/usr/local/etc/oai/spgw.conf
# config interface for spgw
sed -r -i "/SGW_INTERFACE_NAME_FOR_S11/ s-\".*\"-\"${spgw_iface_name}\"-" $spgw_conf
sed -r -i "/SGW_INTERFACE_NAME_FOR_S1U_S12_S4_UP/ s-\"eth0\"-\"${spgw_iface_name}\"-" $spgw_conf
sed -r -i "/PGW_INTERFACE_NAME_FOR_SGI/ s-\".*\"-\"${spgw_iface_name}\"-" $spgw_conf

# config ip for mme and spgw
sed -r -i "/SGW_IPV4_ADDRESS_FOR_S11/ s-\".*\"-\"${spgw_addr}\"-" $spgw_conf
sed -r -i "/SGW_IPV4_ADDRESS_FOR_S1U_S12_S4_UP/ s-\".*\"-\"${spgw_addr}\"-" $spgw_conf
sed -r -i "/PGW_MASQUERADE_SGI/ s-\".*\"-\"yes\"-" $spgw_conf

echo "Configured interface ${spgw_iface_name} with ip ${spgw_addr} for spgw"
