#!/bin/bash
################################################################################
#
# Copyright (c) 2016, EURECOM (www.eurecom.fr)
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this
#    list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
# ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# The views and conclusions contained in the software and documentation are those
# of the authors and should not be interpreted as representing official policies,
# either expressed or implied, of the FreeBSD Project.
#
################################################################################
# file epc-relation-departed
# brief called when the enb-epc relation is removed 
# author  navid.nikaein@eurecom.fr and A. B. Molini 
set -ex
source $CHARM_DIR/utils/common
set_env_paths

TAC=`relation-get TAC`

remote_unit=${JUJU_REMOTE_UNIT//\//-}

rm -f $CHARM_DIR/tac_$remote_unit
#rm -f $CHARM_DIR/.$JUJU_RELATION_ID


if [ -n "$(grep "$JUJU_REMOTE_UNIT" $CHARM_DIR/.tac_list)" ]; then

    tac_line=$(egrep "^$TAC [0-9]+$" $CHARM_DIR/.tac_list)
    tac_num=$(echo "$tac_line" | cut --delimiter=" " -f 2)
    if [ "$tac_num" -gt 1 ]; then
        tac_num=$((tac_num - 1))
        sed -r -i "s/$tac_line/$TAC $tac_num/" $CHARM_DIR/.tac_list
        sed -r -i "s^$JUJU_REMOTE_UNIT^^" $CHARM_DIR/.tac_list
    else
        sed -r -i "/$tac_line/ d" $CHARM_DIR/.tac_list
        sed -r -i "s^$JUJU_REMOTE_UNIT^^" $CHARM_DIR/.tac_list
        if [ "$(egrep -c "MCC[ ]*=[ ]*\"$(config-get gummei_tai_mcc)\"[ ]*;[ ]*MNC[ ]*=[ ]*\"$(config-get gummei_tai_mnc)\"[ ]*;[ ]*TAC[ ]*=[ ]*\"[0-9]*\"" $epc_conf_path/epc.conf)" -gt 1 ]; then


            sed -r -i "/MCC[ ]*=[ ]*\"$(config-get gummei_tai_mcc)\"[ ]*;[ ]*MNC[ ]*=[ ]*\"$(config-get gummei_tai_mnc)\"[ ]*;[ ]*TAC[ ]*=[ ]*\"$TAC\"/ d" $epc_conf_path/epc.conf
            TAI=$(cat $epc_conf_path/epc.conf | egrep "MCC[ ]*=[ ]*\"[0-9]+\"[ ]*;[ ]*MNC[ ]*=[ ]*\"[0-9]+\"[ ]*;[ ]*TAC[ ]*=[ ]*\"[0-9]+\"" | tail -1 | egrep -o "MCC[ ]*=[ ]*\"[0-9]+\"[ ]*;[ ]*MNC[ ]*=[ ]*\"[0-9]+\"[ ]*;[ ]*TAC[ ]*=[ ]*\"[0-9]+\"[^,]*,") || true
            if [ -n "$TAI" ]; then
                TAI=${TAI%\},}
                sed -r -i "/$TAI/ s/([^,]*),/\1/" $epc_conf_path/epc.conf
            fi
        fi

        #now I have to restart the EPC software to take into account the new config file
        hss_id=`relation-ids hss` 
        #FOR THE TIME BEING CONSIDER only one hss service and only one unit
        
        if [ -z "$hss_id" ]; then
           
           juju-log "Can't restart the MME because of the departure of hss "
           exit 0
          
        else
          
           hss_unit=`relation-list -r $hss_id`
           if [ -n "$hss_unit" ]; then
               if [ "$(relation-get -r $hss_id hss_running $hss_unit)" == "no" ]; then
                  exit 0
               fi
           else
                  exit 0
           fi
        fi
        #se ce hss relation e il epc.conf is changed , restart epc but first stop every
        #enb and after epc software is running , start every enb attached to this epc

        #for epc_id in $(relation-ids epc); do
        #    juju-log ""$epc_id""
        #    if [ "$epc_id" != "$JUJU_RELATION_ID" ]; then
        #        relation-set -r "$epc_id" epc_running=no
        #    fi
        #done

        $CHARM_DIR/hooks/start

        for epc_id in $(relation-ids epc); do
           juju-log ""$epc_id""
           #this because we can't set relation  data for the current departing relation anylonger
           if [ "$epc_id" != "$JUJU_RELATION_ID" ]; then
              restart=`relation-get -r $epc_id trigger_restart $JUJU_UNIT_NAME`
              relation-set -r $epc_id trigger_restart=$(($((restart + 1)) % 10))
              relation-set -r $epc_id epc_running=yes
           fi
        done
    #this is to establish a new s1 link in order to comunicate the new TAI list to the enodeb
    fi
fi

