#!/bin/bash
################################################################################
#
# Copyright (c) 2016, EURECOM (www.eurecom.fr)
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this
#    list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
# ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# The views and conclusions contained in the software and documentation are those
# of the authors and should not be interpreted as representing official policies,
# either expressed or implied, of the FreeBSD Project.
#
################################################################################
# file epc-relation-joined 
# brief called when the enb-epc relation is created 
# author navid.nikaein@eurecom.fr and A. B. Molini  
set -eux
source $CHARM_DIR/utils/common

juju-log "Setting up relation settings for OAISIM charm"
relation-set TAC=`config-get gummei_tai_tac`

#we choose the plmn when we deploy the mme and based on which
#mme we link this oaisim, it will belong to a certain TA.
relation-set MCC=`config-get gummei_tai_mcc`
relation-set MNC=`config-get gummei_tai_mnc`
relation-set trigger_restart=0

mme_public_ip=`unit-get public-address`
get_ip_address $mme_public_ip
status=$?
if [ "$status" == "1" ] ; then
    status-set error "nslookup failed for the mme host name ($mme_public_ip)"
    relation-set mme_ip=$mme_public_ip
else
    relation-set mme_ip=$validated_mme_public_ip
fi 

#check_epc_process
#if [ "$status" -eq 0 ]; then
#   check_epc_connection
#   if [ "$COUNTER" -lt 30 ]; then
#   relation-set epc_running=yes
#   fi
#else
   relation-set epc_running=no
#we say a priori that epc is not running just to force
#enb to actually run only if the tac is in the tai list or 
#after having verified that is so.

