#!/bin/bash
################################################################################
#
# Copyright (c) 2016, EURECOM (www.eurecom.fr)
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this
#    list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
# ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# The views and conclusions contained in the software and documentation are those
# of the authors and should not be interpreted as representing official policies,
# either expressed or implied, of the FreeBSD Project.
#
################################################################################
# file stop 
# brief stop the oai-epc service, this happens when the service is stopped/disabled
# author  navid.nikaein@eurecom.fr and A. B. Molini   

set -eux
source $CHARM_DIR/utils/common
set_env_paths

juju-log "Stopping EPC service in this unit"
#service mme_gw stop || true
service epc_mme stop || true
service epc_spgw stop || true

juju-log "Deleting the EPC stdout and stderr files"
rm -f /srv/.out /srv/.err


juju-log "Cleaning up the openair-cn installation directory..."
rm -rf $openair_path
juju-log "Openair-cn removed"


juju-log "Removing EPC final executable..."
#rm -f /usr/local/bin/$epc_exec_name
rm -f /usr/local/bin/$epc_exec_mme
rm -f /usr/local/bin/$epc_exec_spgw
juju-log "Removing configuration file installed along side the system..."
rm -rf /usr/local/etc/oai/
juju-log "Done"

if [ -d /usr/lib/freeDiameter ]; then
      FREEDIAMETER_PREFIX=/usr
  elif [ -d /usr/local/lib/freeDiameter ]; then
      FREEDIAMETER_PREFIX=/usr/local
fi
juju-log "Removing EPC freediameter files"

rm -f $FREEDIAMETER_PREFIX/etc/freeDiameter/mme*    2>&1

juju-log "Restoring previous /etc/hosts file..."
install -o root -g root -m 0644 /home/hosts /etc/

juju-log "Removing Upstart script from the system..."
#rm -f /etc/init/mme_gw.conf
rm -f /etc/init/epc_mme.conf
rm -f /etc/init/epc_spgw.conf
#rm -f /etc/init/mme_gw.conf
